[package]
name = "rofi-websearch"
version = "0.1.0"
edition = "2024"

[dependencies]
rofi-mode = "0.4.1"
rofi-plugin-sys = "0.5.0"
serde = { version = "1", features = ["derive"] }
urlencoding = "2.1.3"
serde_json = "1"
dirs = "6"

[lib]
crate-type = ["cdylib"]
