[package]
name = "rofi-websearch"
version = "0.1.0"
edition = "2024"

[dependencies]
rofi-mode = "0.4.1"
rofi-plugin-sys = "0.5.0"
search_engines = {path = "../search_engines"}
phf = "0.11.3"

[lib]
crate-type = ["cdylib"]
